apiVersion: v1
kind: Service
metadata:
  name: velero
  labels:
    k8s-app: velero
spec:
  ports:
  - name: metrics
    port: 8085
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: velero
