namespace: kube-system

configurations:
  - kustomize-config.yaml

bases:
  - ../velero-base

images:
  - name: velero/velero-plugin-for-aws
    newTag: v1.0.0

patchesStrategicMerge:
  - plugin-patch.yaml

resources:
  - minio/
  - storageLocation.yaml
