apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
spec:
  template:
    spec:
      initContainers:
      - image: velero/velero-plugin-for-aws
        imagePullPolicy: Always
        name: velero-plugin
        volumeMounts:
        - mountPath: /target
          name: plugins
      - name: wait-for-minio-setup
        image: groundnuty/k8s-wait-for:v1.2
        imagePullPolicy: Always
        args: ["job", "$(MINIO_SETUP_JOB_NAME)"]
