apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-minio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wait-for-minio
rules:
- apiGroups:
  - ""
  resourceNames:
  - minio-0
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-setup:wait-for-minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wait-for-minio
subjects:
- kind: ServiceAccount
  name: wait-for-minio