apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    k8s-app: minio
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    k8s-app: minio
