apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
spec:
  template:
    spec:
      initContainers:
      - image: velero/velero-plugin-for-aws
        imagePullPolicy: Always
        name: velero-plugin
        resources: {}
        volumeMounts:
        - mountPath: /target
          name: plugins
