# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  module.kfd.sighup.io/name: "dr"
  module.kfd.sighup.io/version: "v1.9.0"
  module.kfd.sighup.io/component: "velero-on-prem"
  kfd.sighup.io/source: "kustomize"

configurations:
  - kustomize-config.yaml

images:
  - name: velero/velero-plugin-for-aws
    newName: registry.sighup.io/fury/velero/velero-plugin-for-aws
    newTag: v1.3.0
  - name: groundnuty/k8s-wait-for
    newName: registry.sighup.io/fury/groundnuty/k8s-wait-for
    newTag: v1.5.1


patchesStrategicMerge:
  - plugin-patch.yaml

resources:
  - ../velero-base
  - minio/
  - storageLocation.yaml
