apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    app: velero
  name: default
spec:
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: "http://$(MINIO_STS_NAME)-0.$(MINIO_SERVICE_NAME).$(MINIO_NAMESPACE).svc.cluster.local:9000"
  objectStorage:
    bucket: "$(MINIO_NAMESPACE)"
  provider: aws
